### ISSUE TITLE
trying to use non deterministic function now() 

### ISSUE THREAD

**Issue by shantanuharkut** [greenlion/swanhart-tools#110]
Hi ,

I am trying to use now() function in where clause but when i use php convert.php script , it creates file without error but it skip bracket after now causing error in creating materialize view. But when I put it manually in where clause like below it works. 

Can we get this bracket from convert.php file itself.

CALL flexviews.create('accounts', 'weekly_data', 'INCREMENTAL');
SET @mvid := LAST_INSERT_ID();
CALL flexviews.add_expr(@mvid,'MAX','tdate','tdate');
CALL flexviews.add_expr(@mvid,'GROUP','account_id','account_id');
CALL flexviews.add_expr(@mvid,'SUM','visits','visits');

CALL flexviews.add_table(@mvid,'accounts','daily_data',daily_data',NULL);
CALL flexviews.add_expr(@mvid,'WHERE','tdate >= NOW() - INTERVAL 7 DAY','where_clause');
CALL flexviews.enable(@mvid);

**Comment by shantanuharkut** [comment]
Please provide update.

**Comment by greenlion** [comment]
I'm really not sure that NOW() in the WHERE clause will work like you expect it to.  I've never tested non-deterministic functions and don't expect them to work.

**Comment by mvid** [comment]
Please place code examples in code blocks so that people don't accidentally get @ notified. 

Thanks :)

**Comment by Farren246** [comment]
Have you considered running the non-deterministic function and applying its result to a variable, then inserting that variable in to the resulting scripts? If the goal is to have queries based on NOW(), then NOW() should be defined as the datetime at the time that the query is submitted, or at least, as close to that point in time.
