### ISSUE TITLE
Unable to make AVG function to work in flexviews

### ISSUE THREAD

**Issue by gamer154** [greenlion/swanhart-tools#112]
Hello,

I am unable to get the AVG function to work in flexviews. I am adding the expression into the table properly but the error I am getting is; 08:45:08	call flexviews.enable(@mvid1)	Error Code: 1644. COULD NOT VALIDATE MATERIALIZED VIEW.  CHECK @MV_DEBUG.	0.110 sec

I can't seem to find @MV_DEBUG. I am not sure where that error is pointing towards. If there is a way to debug or troubleshoot it then please let me know. Here is the snippet of code that I am trying to execute;

-- Code Start
delete from flexviews.mview;
drop database if exists test;

create database if not exists test;

use test;

drop table if exists t1;

create table test.t1(
c1 int,
c2 int)
engine=innodb;

insert into test.t1 values (1,1);
insert into test.t1 values (2,2);

call flexviews.create_mvlog('test','t1');

call flexviews.create('test','mv1','INCREMENTAL');
set @mvid1 := last_insert_id();

call flexviews.add_table(@mvid1, 'test','t1', 't1', null);
-- call flexviews.add_expr(@mvid1, 'SUM','t1.c1','the_sum');
call flexviews.add_expr(@mvid1, 'AVG','t1.c1','the_avg');

call flexviews.enable(@mvid1);

select * from test.mv1;
-- Code end

I am testing the flexviews to understand how it works. The SUM and count function works properly in add_expr but AVG and Percentile functions do not work for me. Please let me know what I can do to troubleshoot the issue. Thanks in advance.

**Comment by greenlion** [comment]
Hi,

I'll check this out as soon as possible.  In the meantime, to check
@MV_DEBUG run:

[code]
SELECT @MV_DEBUG;
[/code]

**Comment by gamer154** [comment]
Here is the result of select @mv_debug;

'SELECT  NULL as mview$pk, AVG(t1.c1) as `the_avg`,SUM(t1.c1) as `the_avg`_sum,COUNT(t1.c1) as `the_avg`_cnt\nFROM  test.t1 as `t1`  LIMIT 0'

So to me it seems like that is the same result as select get_sql(@mvid1); Somewhere in the code it is not parsing the data properly? Not too sure to be honest. Thanks again for the help.

**Comment by greenlion** [comment]
Hi,

Hmm, there is a \n in there that should be a literal newline.
 the_avg_cnt\nFROM is not valid SQL :)

I'll figure out where that is coming from and get back to you.

--Justin

**Comment by gamer154** [comment]
Thank you so much for the assistance.

**Comment by greenlion** [comment]
I've checked the fix into git.  To import the fix, change to
swanhart-tools/flexviews and run:
git pull
mysql -uroot flexviews < procs/get_select.sql
mysql -uroot flexviews < procs/delta.sql

Regards,

--Justin

**Comment by gamer154** [comment]
Thanks for the quick fix. I ran the script again and I am facing the following error; 
call flexviews.enable(@mvid1)	Error Code: 1072. Key column 'mview$hash' doesn't exist in table	

I have the same issue when I change the expression to PERCENTILE_95 function. Thanks again for the help and any help would be appreciated.

**Comment by greenlion** [comment]
Hi,

There is an "orphaned" expression in your view now, that isn't resolved by
the fix to delta.sql.  Either delete from flexviews.mview and re-run your
test (recreate the view) or run the following:
DELETE FROM flexviews.mview_expression where mview_expression =
'mview$hash';

**Comment by greenlion** [comment]
Hi,

Just so you know: Flexviews adds a mview$hash column to views that don't
use aggregate expressions.   The index for the mview$hash column is added
in flexviews.enable() but it is only supposed to be added to views that
don't have aggregate functions.  The flexviews.has_aggregates() function
was incorrectly identifying a view with only AVG expressions as having no
aggregate functions, so flexviews.enable() added the KEY to your view.  I
fixed has_aggregates() but that doesn't remove the KEY expression that was
previously added when you called flexviews.enable()

I hope that clears things up :)

**Comment by gamer154** [comment]
Well, I just uninstalled flexviews, reinstalled it and I am getting the same error. It is a new flexviews DB instance so it should not have any old information, right? Do I need to git pull again to get the new has_aggregates() function? I believe three files were changed so I am guessing that one of them was that one. Is there any other debugging functions I can run to troubleshoot this issue? Thanks again for all the help!

**Comment by greenlion** [comment]
Hi,

It would help if I actually pushed the code.  I only pushed get_select.sql,
not delta.sql..  Do a git pull, import delta.sql and then recreate the view
or delete the key and enable it.

Sorry about that.  I'm was a little distracted by my real job :)

--Justin

**Comment by gamer154** [comment]
No problem Justin and thanks a lot for all the help. Sorry for the bother as well. I am still testing it out. I will report back with result when I do a new installation. Thanks again.

**Comment by gamer154** [comment]
After doing a whole new installation of flexviews, the average function and percentile functions are working. Thank you so much for the help. You may close the thread. Thanks again for all the help!
