### ISSUE TITLE
Error during the Shard-Query setup

### ISSUE THREAD

**Issue by sasidhar79** [greenlion/swanhart-tools#113]
Hi 

While installing the Shard-Query as I was configuring with following 

php setup_virtual_schema.php --ini=bootstrap.ini

I was getting the following error 

PHP Fatal error:  Uncaught exception 'Exception' with message '
ERROR: CURL extension not available and dynamic loading failed

' in /usr/share/shard-query/include/S3.php:39
Stack trace:
#0 /usr/share/shard-query/include/shard-loader.php(31): require_once()
#1 /usr/share/shard-query/include/shard-query.php(36): require_once('/usr/share/shar...')
#2 /usr/share/shard-query/setup_virtual_schema.php(6): require_once('/usr/share/shar...')
#3 {main}
  thrown in /usr/share/shard-query/include/S3.php on line 39

please let me know how I can resolve this

thank you

sasi

**Comment by sasidhar79** [comment]
figured it out , I had to install cURL and once did i was able to progress

**Comment by greenlion** [comment]
Thanks for the report.  I'll make the S3 support detect curl and disable use of s3 if you don't have it.

--Justin
