### ISSUE TITLE
no default schedule is created in the two schedule tables on mview creation

### ISSUE THREAD

**Issue by vesper8** [greenlion/swanhart-tools#115]
In the documentation it says that upon view creation a default schedule is created in mview_apply_schedule and mview_compute_schedule but this does not happen.

Also in the stored procedures there is nowhere with an INSERT statement in either of those two tables.

I am trying to figure out a good way to periodically refresh my mviews and I was trying to use your provided build_mviews.php but this does not work because of the above issue. The build_mviews.php script depends on the schedule tables being populated.

Is there an example of a proper solution for keeping the mviews refreshed.. IE is there something like your build_mviews.php but that actually works with the current release?

I would really appreciate this.

Thanks!

**Comment by greenlion** [comment]
There are events in the events/ dir which refresh all views.  You can modify those to use the refresh and compute schedule tables and only refresh views that need to be refreshed. If you don't want to do that (or can't because you are unfamiliar with stored routines and events) left me know and I'll work on the modifications when I can, probably this weekend.

**Comment by vesper8** [comment]
Thank you for the offer. I may take you up on it.. for now I am still struggling to get this to work properly. I am wondering if the huge amount of notices/warnings I'm getting from the consumer process may have something to do with why my refreshes keep failing or timing out.

Thanks for pointing out the events too.. I was not familiar with mysql events but I am reading about them now.

The output log for consumer_safe.sh is getting a ton of these warnings/notices:

``
PHP Strict Standards:  Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /usr/share/php/Console/Getopt.php on line 109
PHP Strict Standards:  Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /usr/share/php/Console/Getopt.php on line 154

PHP Notice:  Undefined index: database_nametable_namenumber in /path/to/swanhart-tools-master/flexviews/consumer/include/flexcdc.php on line 393
PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /path/to/swanhart-tools-master/flexviews/consumer/include/flexcdc.php on line 379
``

The last two in particular, which have to do with the internal caching it seems.. has created over 10k log entries in just a few hours.

Perhaps it is because I am not adding indexes/uniques properly in my mview creation.

I would certainly love to be able to ask a few more questions because I really want to like and use flexviews. Could we chat on skype perhaps? You can add me if you want "vesper8 on skype"

**Comment by greenlion** [comment]
I will check out the undefined index warnings.  That may impact performance.  I have already fixed the PEAR "errors" in strict mode.  

It looks like perhaps the connection was lost to the db for the last warning.  I added mysqli_ping() calls awhile back that should resolve that.

I will open a separate issue for the warnings and close this.
