### ISSUE TITLE
Can't login to UI

### ISSUE THREAD

**Issue by ivarbanov** [greenlion/swanhart-tools#119]
Hello guys,

I can't login to web ui. I did installation. I can see a login prompt when I try to access http://ip/shard-query but when I tried user and mpp I can't login. The error in the httpd log files are:

[Mon Jun 22 23:08:01 2015] [error] [client 10.64.10.20] PHP Notice:  Undefined index: authName in /usr/share/dooframework/uri/DooUriRouter.php on line 180
[Mon Jun 22 23:08:03 2015] [error] [client 10.64.10.20] PHP Warning:  file_get_contents(protected/config/user.inc): failed to open stream: No such file or directory in /usr/share/shard-query/ui/protected/config/routes.conf.php on line 59

Can you please help me out with this? I have no idea about php so any help is much appreciated!

Thank you in advance!

**Comment by burn1brain** [comment]
Never mind. I resolved this. It was needed to run php set-password.php to ask you to set the user and password.

Thank you.

**Comment by jdshewey** [comment]
I also could not log in to the UI. I had to change the code of set_password.php to:

<?php
echo "Enter username (user):";
$user = trim(fgets(STDIN));
echo "Enter password (mpp):";
$pass = trim(fgets(STDIN));

if($user=="") $user="user";
if($pass=="") $pass="mpp";

$cred = array($user => $pass);
file_put_contents("protected/config/user.inc", serialize($cred));
?>

And then I also had to change the ownership of /usr/share/shard-query/ui/protected/config/user.inc back to apache:apache.

**Comment by greenlion** [comment]
Thank you for the report and fix.  I will apply next week, busy with other things this week.

**Comment by greenlion** [comment]
I need to check to see if this is fixed or not.

TODO.

**Comment by greenlion** [comment]
not a bug
