### ISSUE TITLE
setup_flexcdc fails in AWS RDS due to  'FLUSH TABLES WITH READ LOCK'

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [greenlion/swanhart-tools#120]
setup_flexcdc.php fails with Access Denied error as it is trying to acquire global lock by executing the statement: FLUSH TABLES WITH READ LOCK. It seems this is prohibited in AWS RDS.

Please suggest a work-around for RDS.

**Comment by greenlion** [comment]
Create an EC2 instance (medium will probably do) and set it up as a slave, and use that to capture changes.

FlexCDC requires both FLUSH TABLES WITH READ LOCK and SET SQL_LOG_BIN=0, neither of which RDS supports because RDS is not 100% MySQL compatible.

**Comment by nagarajanchinnasamy** [comment]
Hi, Thanks for the response.

I could not find any (official) way of setting up a MySQL slave (external to RDS) of an RDS Master. It would be helpful if you can pass on any reference to this.

Also, `flexcdc.php`, in addition to creating some internal tables, it seems to be updating `binlog_consumer_status` table with current master position (Thats where it calls `FLUSH TABLES`). Just wondering if there is any way i can obtain this info manually and pass this as a param to `setup` function - so that i can avoid this error and proceed???
