### ISSUE TITLE
mysql-bin.000001: Text file busy

### ISSUE THREAD

**Issue by OlapPhil** [greenlion/swanhart-tools#121]
Hi,

Firstly, if this isn't the suitable place for setup related questions, could you point me to the preferred place please?

I'm using Flexviews 1.6.1, MySQL 5.1.61 and PHP 5.4.24.  I'm trying to get flexCDC working.

I'm getting the following when running ./consumer_safe.sh --ini=consumer.ini

 /usr/local/mysql_recovery/binlogs/mysql-bin.000001: Text file busy

Any idea what I have done wrong?  MySQL is run as the mysql user, the files are owned by the mysql user and i'm running consumer_safe.sh as the mysql user.

I did notice that the example ini file contained this, where as mine contains the actual log file;
mysqlbinlog=/usr/local/mysql/bin/mysqlbinlog
 However, when I tried it with just the directory, the process failed stating that it was a directory.

Any help would be much appreciated.

regards,
Phil

**Comment by greenlion** [comment]
That has to point to the mysqlbinlog binary, not the binary log.  You need to use recent 5.6 version (last four or five minor versions) of mysqlbinlog. if you use an older version of MySQL or MariaDB, you need 5.6 to download the recent mysqlbinlog binary for DECIMAL column support.  

Just grab tarball and extract, then put mysqlbinlog where you want and update .ini

**Comment by greenlion** [comment]
Also get Git master.  6.1 is very old and because there is little interest in the tool I have not packaged new version.

**Comment by OlapPhil** [comment]
That worked perfectly, thank you.
