### ISSUE TITLE
Flexviews Support

### ISSUE THREAD

**Issue by jamiejackson** [greenlion/swanhart-tools#125]
I'm trying out Flexviews, and I'm having a hard time due to the lack of any kind of support venue.

Is there something that I'm not aware of? If there isn't, and If nobody has mentioned this as a barrier to entry, I'm doing so now. (Nobody *seems* to know about Flexviews in #mysql or #maria, on Freenode IRC, by the way.) Also, without any sort of central place to "huddle," it's really hard for me to figure out how solid/supported/used this technology is.

*Assuming* that I didn't miss some known support avenue (if there indeed isn't one), what do you think about establishing, say, a Google group?

**Comment by greenlion** [comment]
There is some info on the MariaDB knowledge base.  Other than that, info is rather sparse.  It is an old project but it never gained much traction, though it works quite well.
