### ISSUE TITLE
Flexviews: Completely Remove a MV?

### ISSUE THREAD

**Issue by jamiejackson** [greenlion/swanhart-tools#130]
I don't see an option for removing an MV, with the closest thing being, maybe, a disable/rename combo. Am I understanding that correctly? Also, if there isn't such a remove option, why is that?

**Comment by greenlion** [comment]
I just felt there isn't really any overhead in keeping the metadata for a disabled view, in case you want to re-enable it.  I disable/enable views for testing all of the time.  I can add a mv_zap procedure that deletes all the metadata for a view if you want one.

**Comment by greenlion** [comment]
function not requested.  closing.
