### ISSUE TITLE
Flexviews: OUTER JOIN Warning

### ISSUE THREAD

**Issue by jamiejackson** [greenlion/swanhart-tools#131]
From the [part one blog](https://www.percona.com/blog/2011/03/23/using-flexviews-part-one-introduction-to-materialized-views/):

>And some drawbacks:
>
> * Not all SQL syntax supported (no outer join), no non-deterministic functions, etc.
> * There is overhead for change-data capture.
> * Some extra storage is used for the changes and deltas.
> * Creating an MV is not as simple as I’d like.

*I realize that this is ignorance on my part*, but when I read "outer join," I didn't think left/right join, since I never use the term "outer join," personally. When I read that, I think my mind translated "outer join" to "cross join."

I've been trying to get a MV going for a few days now, and have struggled along the way. I couldn't get the MV to populate on enable. I figured out what was going on only now, because I looked at `@mv_debug` and diffed it with the original, to find that the "left" keywords had been stripped out (turning everything into inner joins, and yielding zero rows).

Two things\* could have helped me:

* An explicit mention of left/right in the docs (i.e., the blogs, which serve as most of the documentation).
* A warning/error from convert.php that outer (left/right) joins aren't supported, instead of a quiet conversion to inner joins.

**Comment by greenlion** [comment]
convert.php is kind of unmaintained (by which I mean totally unmaintained) but I'll see what I can do. (and document that fact)

Unfortunately I can't change the blogs.  I no longer am employed by Percona.
