### ISSUE TITLE
Starting MySQL Proxy per instruction in install doc

### ISSUE THREAD

**Issue by ehardway** [greenlion/swanhart-tools#132]
Hi, 
I am attempting to use Shard Query for the first time.
I am trying get the MySQL proxy going per the instruction in the INSTALL file. 

"Download and install MySQL proxy in /usr/local/mysql-proxy.
Start the proxy and use the -s option to point the proxy to the Shard-Query LUA script:
mysql-proxy -P 127.0.0.1:4042 -b 127.0.0.1:3306 -s /usr/share/shard-query/proxy/mysqlproxy.lua --admin-username=root --admin-password=admin --admin-lua-script=/usr/local/lib/mysql-proxy/lua/admin.lua --daemon --log-file=/usr/share/shard-query/log/proxy.log"

Here is what I am trying 
 sudo /usr/local/mysql-proxy/bin/mysql-proxy -P 127.0.0.1:4042 -b 127.0.0.1:3306 -s /opt/lua/mysqlproxy.lua --admin-username=root --admin-password=admin --admin-lua-script=/opt/lua/admin.lua

I get the following error when I run the above. 
2015-09-25 14:02:27: (critical) mysql-proxy-cli.c:505: Unknown option --admin-username=root (use --help to show all options)

It seems that admin-username , admin-password and admin-lua-script or not valid options for mysql proxy. 

Please advise as to what I am doing wrong.

Below is information on the version of proxy that I am using on Debian 8. 

Thanks EricH

/usr/local/mysql-proxy$ sudo /usr/local/mysql-proxy/bin/mysql-proxy --help
Usage:
  mysql-proxy [OPTION...] - MySQL Proxy

Help Options:
  -?, --help                                              Show help options
  --help-all                                              Show all help options
  --help-proxy                                            Show options for the proxy-module

Application Options:
  -V, --version                                           Show version
  --defaults-file=<file>                                  configuration file
  --verbose-shutdown                                      Always log the exit code when shutting down
  --daemon                                                Start in daemon-mode
  --user=<user>                                           Run mysql-proxy as user
  --basedir=<absolute path>                               Base directory to prepend to relative paths in the config
  --pid-file=<file>                                       PID file in case we are started as daemon
  --plugin-dir=<path>                                     path to the plugins
  --plugins=<name>                                        plugins to load
  --log-level=(error|warning|info|message|debug)          log all messages of level ... or higher
  --log-file=<file>                                       log all messages in a file
  --log-use-syslog                                        log all messages to syslog
  --log-backtrace-on-crash                                try to invoke debugger on crash
  --keepalive                                             try to restart the proxy if it crashed
  --max-open-files                                        maximum number of open files (ulimit -n)
  --event-threads                                         number of event-handling threads (default: 1)
  --lua-path=<...>                                        set the LUA_PATH
  --lua-cpath=<...>                                       set the LUA_CPATH

 sudo /usr/local/mysql-proxy/bin/mysql-proxy --version
mysql-proxy 0.8.5
  chassis: 0.8.5
  glib2: 2.16.6
  libevent: 2.0.21-stable
  LUA: Lua 5.1.4
    package.path: /usr/local/mysql-proxy/lib/mysql-proxy/lua/?.lua;
    package.cpath: /usr/local/mysql-proxy/lib/mysql-proxy/lua/?.so;
-- modules
  proxy: 0.8.5

**Comment by greenlion** [comment]
use --help-proxy that should tell you the new command line options to use
