### ISSUE TITLE
SIGNAL ID NOT FOUND (FlexCDC consumer is likely behind)

### ISSUE THREAD

**Issue by yangzhangheng** [greenlion/swanhart-tools#134]
call flexviews.refresh(flexviews.get_id('flexviews','mv_icd_code'), 'BOTH', NULL);
[Err] 1644 - ERROR: SIGNAL ID NOT FOUND (FlexCDC consumer is likely behind)

flexcdc.err no error info.

**Comment by greenlion** [comment]
Do you have the MySQL 5.6 or 5.7 mysqlbinlog utility?  It will not work with MariaDB mysqlbinlog because it is buggy (same with <5.6).

If not, get 5.7 mysqlbinlog, point to it in your flexcdc.ini file and reinstall flexcdc (run installer with -f option)

**Comment by yangzhangheng** [comment]
F:\tools\flexviews\flexviews\consumer>php setup_flexcdc.php -f
PHP Fatal error:  Cannot use object of type PEAR_Error as array in F:\tools\flex
views\flexviews\consumer\setup_flexcdc.php on line 16

**Comment by greenlion** [comment]
Just drop the flexviews database and run the install script.

**Comment by yangzhangheng** [comment]
Just drop the flexviews database and run the install script.
with param -f :
F:\tools\flexviews\flexviews\consumer>php setup_flexcdc.php -f
PHP Fatal error:  Cannot use object of type PEAR_Error as array in F:\tools\flex
views\flexviews\consumer\setup_flexcdc.php on line 16

no param -f:
F:\tools\flexviews\flexviews\consumer>php setup_flexcdc.php
系统找不到指定的路径(system not found the path)。
mysqlbinlog=/cygdrive/f/temp/bin/mysqlbinlog
database=flexviews
error_log=flexcdc.err
binlog_consumer_status=binlog_consumer_status
mvlogs=mvlogs
mview_uow=mview_uow
log_retention_interval=10 DAY
skip_before_update=
mark_updates=
auto_changelog=
raise_warnings=
bulk_insert=1
sleep_increment=.25
sleep_maximum=5
failure_sleep_time=30
failure_log_file=flex_cdc_log.log
failure_email_address=root@localhost
setup starting
setup completed

**Comment by greenlion** [comment]
windows is not supported
