### ISSUE TITLE
Im just lost TBH, how do you use this ?  using php7

### ISSUE THREAD

**Issue by collmomo** [greenlion/swanhart-tools#145]
I can't find on the web a simple clean demonstration on how to use this library. I did the installation after much struggle looking through many pages of google but now How do you use it lol ? 

Look here: http://stackoverflow.com/questions/36805578/mysql-slow-query-10-seconds/36805780#36805780

This is the query that I would like to transform into one big indexed view aka materialized view aka mysql flexviews. 

Like your blog posts are clear for telling us how it works but I would like to know how to use it in a real world example.

In fact after trying to import install.sql, Im getting the following errors:

`ERROR 1644 (45000): TABLE NOT EXISTS OR ACCESS DENIED
ERROR 1146 (42S02): Table 'flexviews.mvlog_3b0cef8fb9788ab03163cf02b19918d1' doesn't exist
ERROR 1146 (42S02): Table 'flexviews.mvlog_3b0cef8fb9788ab03163cf02b19918d1' doesn't exist`

And many `PHP Notice:  Uninitialized string offset: 0 in swanhart-tools/flexviews/consumer/include/flexcdc.php on line 1259`

**Posted the issue on Stackoverflow:**
http://stackoverflow.com/questions/36818585/flexview-install-procedure-undefined-index

I have posted everything I did since I cloned your git.

**Comment by pablorocka** [comment]
Hey collmomo, I just came across this and I used this video as guide: https://www.youtube.com/watch?v=WhkHMkY80nQ
It worked fine for me using Ubuntu 16.04 / PHP 7. but I also got that PHP Notice when sourcing the install.sql
