### ISSUE TITLE
[fv-request] Procedure to materialize system tables

### ISSUE THREAD

**Issue by federico-razzoli** [greenlion/swanhart-tools#146]
Currently system tables can be materialized (not incrementally, of course). But if one wants to materialize multiple tables it is quite verbose. Unless one wants WHERE clauses, etc, a very generic procedure would be convenient.

Suggestion:

materialize_system_tables(<db_name>, <table_name_pattern>, <interval>)

Examples:

CALL materialize_system_tables('information_schema', '%STATISTICS', 60 \* 60 \* 2);
CALL materialize_system_tables('performance_schema', 'events_waits%', 60);

(Should probably materialize any table, not incrementally, but it is convenient for system tables)

**Comment by greenlion** [comment]
If you want to keep a history of these, look at my tool PS_HISTORY which is specialized to collect this data into history tables.
