### ISSUE TITLE
Row updates not getting inserted into flexviews tables.

### ISSUE THREAD

**Issue by rohan-shimpi** [greenlion/swanhart-tools#150]
I followed the steps described in the following link,
https://www.percona.com/blog/2011/03/25/using-flexviews-part-two-change-data-capture/
The tables are created in the flexviews schema using the add_tables.php, but no data inserted into the tables after data manipulation. There are no errors shown when running the consumer script I can see the insert statements in the binary log files.
How can I verify that the consumer script is running correctly and why flexviews tables are not updated?

Thanks

**Comment by greenlion** [comment]
You should do two things:
1) modify include/flexcdc.php and change debug=false to debug=true in the function that executes MySQL queries.  there is only one debug=false in the codebase as far as I remember

2) php run_consumer.php

This will print out all the SQL executed, as well as stop on any errors.  You should see INSERT statements into the change log table. The last statement that prints before exit likely has some sort of error.  

Let me know what the error is.

**Comment by rohan-shimpi** [comment]
Thank you for your reply.
I followed the above steps and got the following error message
error from mysqlbinlog: ERROR: Got error reading packet from server: Misconfigured master - server_id was not set

But the server id is set which I confirmed using the query 'SHOW GLOBAL VARIABLES'.

Thanks

**Comment by greenlion** [comment]
It will be set to 1 by default, but not actually set to 1.  I think this is a bug, but it has never been fixed.  Add server_id=22 (or whatever) to your my.cnf

make sure you have:
log_bin=master (or whatever)
server_id=22 (or whatever)
binlog_format=row

I think that should fix it.

**Comment by greenlion** [comment]
It is odd though.  I would expect the setup script to fail if that isn't configured properly.  Either way, the consumer_safe.sh script should exit instead of restarting flexcdc in this case, so that is a bug that I need to fix.

Thanks!

**Comment by rohan-shimpi** [comment]
Thank you for the quick response.
I did the changes to my.cnf file.
Now when I run the run_consumer.php, I can see the data being inserted into the flexviews tables.
But when I run the consumer_safe.sh, the tables are not updated with the latest insert queries.

Thanks

**Comment by greenlion** [comment]
All the .sh script does is run the run_consumer.php script in a loop, so I am not sure how that is possible.

**Comment by rohan-shimpi** [comment]
Yes I saw that script. Even I did not get why it behaves the way it is now.
I just use the php run_consumer.php and it works fine.

Thanks

**Comment by greenlion** [comment]
ok.  if you find a solution to the problem or underlying cause, let me know and I'll fix it, I just can't figure out what would be wrong off the top of my head.

**Comment by rohan-shimpi** [comment]
Yes sure. I will update once I find the cause.
Also is there any way by which we can determine which columns were updated for an update query instead of the whole row.

Thanks

**Comment by greenlion** [comment]
Hi,

You would have to write your own plugin to do so.  There are two example
plugins included.  One sends data to JSON format, the other just prints
data.

--Justin

**Comment by dkrieger** [comment]
Regarding different results when running consumer_safe.sh vs run_consumer.php , if the .sh file has SUID or SGID set, that could cause the script to run with different permissions that may cause this discrepancy.

**Comment by greenlion** [comment]
not a bug
