### ISSUE TITLE
Shard-Query: sq_helper procedure doesn't work

### ISSUE THREAD

**Issue by msestak** [greenlion/swanhart-tools#151]
I tried your example from blog post https://shardquery.com/2015/03/02/access-shard-query-with-the-mysql-client-without-using-mysql-proxy/

```
 mysql> call shard_query.sq_helper("select * from dim_date limit 2", "", 'test','testtab',1,1);
```

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`test`.`testtab`(D_DateKey text,D_Date text,D_DayOfWeek text,D_Month text,D_Year' at line 1

```
mysql> use shard1; select * from dim_date limit 2;
```

works fine. Running it with:

```
php run_query
select * from dim_date limit 2;
```

works too.

Procedure is listed as installed.

```
mysql> SELECT ROUTINE_NAME, ROUTINE_SCHEMA FROM information_schema.routines\G
*************************** 1. row ***************************
ROUTINE_NAME: sq_helper
ROUTINE_SCHEMA: shard_query
*************************** 2. row ***************************
ROUTINE_NAME: sq_throw
ROUTINE_SCHEMA: shard_query
2 rows in set (0.00 sec)
```

Can you point me how to make it work? I just wanted to run some queries against Shard-Query and thought this is the simplest way.

**Comment by greenlion** [comment]
Do you have the gearman UDF installed in MySQL?

**Comment by msestak** [comment]
I installed gearman UDF and installed functions.

    mysql> select gman_servers_set("127.0.0.1:7001");
    +------------------------------------+
    | gman_servers_set("127.0.0.1:7001") |
    +------------------------------------+
    | 127.0.0.1:7001                     |
    +------------------------------------+
     1 row in set (0.00 sec)


    mysql> SELECT * FROM mysql.func;
    +-------------------------+-----+-------------------------+-----------+
    | name                    | ret | dl                      | type      |
    +-------------------------+-----+-------------------------+-----------+
    | gman_do                 |   0 | libgearman_mysql_udf.so | function  |
    | gman_do_high            |   0 | libgearman_mysql_udf.so | function  |
    | gman_do_low             |   0 | libgearman_mysql_udf.so | function  |
    | gman_do_background      |   0 | libgearman_mysql_udf.so | function  |
    | gman_do_high_background |   0 | libgearman_mysql_udf.so | function  |
    | gman_do_low_background  |   0 | libgearman_mysql_udf.so | function  |
    | gman_sum                |   2 | libgearman_mysql_udf.so | aggregate |
    | gman_servers_set        |   0 | libgearman_mysql_udf.so | function  |
    +-------------------------+-----+-------------------------+-----------+
    8 rows in set (0.00 sec)

    mysql> call shard_query.sq_helper("select * from dim_date limit 2", "", 'test','testtab',1,1);
    ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`test`.`testtab`(D_DateKey text,D_Date text,D_DayOfWeek text,D_Month text,D_Year' at line 1

**Comment by greenlion** [comment]
Hi,

try doing:
set @sqdebug=true;
call ..

Then send me the output.

Thanks!

**Comment by greenlion** [comment]
oh, and run:
select @sql ;
after the call too

**Comment by greenlion** [comment]
One more thing, do you have the `test` database?
create database if not exists test;

**Comment by msestak** [comment]
I reinstalled Shard-Query on another virtual machine. I installed gearman UDF and installed functions. And I have test database.

    mysql> set @sqdebug=true;
    Query OK, 0 rows affected (0.00 sec)

    mysql> call shard_query.sq_helper("select * from dim_date limit 2", "", 'test','testtab',1,1);
    +---------+---------+
    | @create | @insert |
    +---------+---------+
    | NULL    | NULL    |
    +---------+---------+
    1 row in set (0.01 sec)

    ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
     mysql> select @sql ;
    +------+
    | @sql |
    +------+
    | NULL |
    +------+
    1 row in set (0.00 sec)

Here is routine definition (from information_schema.routines):

```
   proc:begin
  
  declare v_args longtext;

  
  declare v_json longtext;

  
  declare v_table    text;

  
  
  declare v_columns  text;

  
  declare v_values   text;

  
  declare v_pos       int;
  declare v_pos2      int;

  
  
  
  
  if v_remote_schema IS NULL
  then
    set v_remote_schema := ''; 
  end if;
  
  
  set v_table := concat('`',v_into_schema,'`.`',v_into_table,'`');
  if v_sql is null or v_table is null or v_remote_schema is null or v_into_schema is null or v_into_table is null or v_return_result is null or v_drop_table is null 
  then 
    call sq_throw('All arguments are NOT NULL');
  end if;

  set v_args := concat('{"sql":"', v_sql, '","schema_name":"',v_remote_schema,'"}');
  
  set v_json := gman_do('shard_query_worker', v_args);

  
  set v_pos     := locate("[", v_json);
  set v_pos2    := locate("]", v_json);
  set v_columns := substr(v_json, v_pos+1, v_pos2-v_pos-1);

  
  set v_columns := replace(v_columns, '\"', '"');

  
  set v_pos     := locate('[[',v_json);
  set v_pos2    := locate(']]',v_json, v_pos+2);

  
  
  
  set @create := concat('create table temporary',v_table, '(', replace(replace(replace(v_columns, '{"type":250,"name":"',''),'"}',''),',',' text,'),' text)');

  
  set @insert:= concat('insert into ', v_table, ' values ', replace( replace( replace( replace( replace( substr(v_json,v_pos+1,v_pos2-v_pos),'[\','[') ,'\",\"','","') ,'\"]','"]') ,'[' ,'(') ,']',')'));

  if(@sqdebug is not null) then
    select @create, @insert;
  end if;
  prepare stmt from @create;
  execute stmt;
  deallocate prepare stmt;

  prepare stmt from @insert;
  execute stmt;
  deallocate prepare stmt;

  if v_return_result != 0 then
    set @sql := concat("select * from ", v_table);
    prepare stmt from @sql;
    execute stmt;
    deallocate prepare stmt;
  end if;

  if v_drop_table != 0 then
    set @sql := concat('drop table ', v_table);
    prepare stmt from @sql;
    execute stmt;
    deallocate prepare stmt;
  end if;

end
```

**Comment by greenlion** [comment]
Hi,

Are you sure you are using the right gearman port?

gman_do must be returning NULL.  The script should check that, but it does
not. If it does, nothing will work.

add this before the gman_do call:
select v_args;

then try to run:
select gman_do('shard_query_worker', v_args); -- replace v_args with output
from that select

--Justin

**Comment by msestak** [comment]
Hi,

I modified sq_helper to return v_args.

```
mysql> call shard_query.sq_helper2("select * from dim_date limit 2", "", 'test','testtab',1,1);
+-----------------------------------------------------------+
| v_args                                                    |
+-----------------------------------------------------------+
| {"sql":"select * from dim_date limit 2","schema_name":""} |
+-----------------------------------------------------------+
1 row in set (0.01 sec)

+---------+---------+
| @create | @insert |
+---------+---------+
| NULL    | NULL    |
+---------+---------+
1 row in set (0.01 sec)

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
```

```
mysql> select gman_do('shard_query_worker', '"sql":"select * from dim_date limit 2","schema_name":""');
+------------------------------------------------------------------------------------------+
| gman_do('shard_query_worker', '"sql":"select * from dim_date limit 2","schema_name":""') |
+------------------------------------------------------------------------------------------+
| NULL                                                                                     |
+------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

I'm using default setup for gearman:

    gearmand -d -p 7001 -L 127.0.0.1

**Comment by greenlion** [comment]
It is not my code that is broken, so I can't help.  Double check that gearman is actually on port 7001 - my guess is that it is not.  Use the port you selected when setting up shard-query.  If it is 7001 then there is a bug in udf.

Sorry.

**Comment by greenlion** [comment]
I missed gearman command line.  Did you compile the gearman UDF yourself?  I had this problem with binary version in past.  Try compiling it and using that version.

**Comment by greenlion** [comment]
not a bug
