### ISSUE TITLE
Flexviews stores database passwords in config file, any alternative?

### ISSUE THREAD

**Issue by gla1** [greenlion/swanhart-tools#152]
Is there any other way to authenticate flexviews with the database than storing plaintext passwords for accounts with elevated privileges in a config file? 

This is a big security hole even with permissions properly locked down on the consumer.ini file. It doesn't seem to support using the unix_socket plugin for MariaDB or anything else I can think of. Any options I'm not thinking of?

**Comment by greenlion** [comment]
I wish the PHP mysqlnd extension had a way to authenticate with a mySQL hash instead of only providing a plain text password.  

Point me at the MariaDB plugin and I can add support for it.  That is likely the best solution at the moment.

**Comment by greenlion** [comment]
Another option is to take the credentials via environment variables.  You would have to manually set the variables before starting the daemon.

Making the .ini owned by a user that has no shell is the safest thing you can do otherwise.  Only root and the service user can access the password in that situation.

**Comment by gla1** [comment]
Thanks for the quick and helpful response! 

Your suggestion for having it owned by a noshell user is pretty good, we're running that past our security team as an option. 

Here's a link to the plugin manual page, sorry I can't do you one better. This would definitely be the ideal solution, so if you do end up implementing it I'd be very grateful. It should work with the MariaDB Authentication Plugin API (documentation for that linked inside of this link), so that might be another option to go for as a starting point. 

https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/

**Comment by greenlion** [comment]
Hi,

It appears that the plugin works through the normal unix domain sockets
interface to mysql.

I believe you can connect to the socket using the following syntax:
[source]
host=localhost

[dest]
host=localhost

The MySQL client will automatically try to use unix domain sockets when the
special host "localhost"
is used.  Note that the default mysql socket location will be used.  If you
put your socket in a
non-default location (many OS packages do) then you will likely need to
update your php.ini to
point to the proper location.  The documentation for this can be found on
the PHP site
here: http://php.net/manual/en/mysqli.quickstart.connections.php

**Comment by gla1** [comment]
Using PHP 5.3.6 with everything properly configured in PHP.ini, I get the following error when attempting to connect with just the host set:

**Comment by greenlion** [comment]
I'll fix that.

**Comment by gla1** [comment]
Using PHP 5.3.6 with everything properly configured in the php.ini, and the consumer.ini set with everything blank but host (have also tried with user set), I get the following error: 

PHP Warning:  mysqli_connect() expects parameter 5 to be long, string given in /IDM/u65/flexviews/product/flexviews/consumer/include/flexcdc.php on line 212

Warning: mysqli_connect() expects parameter 5 to be long, string given in /IDM/u65/flexviews/product/flexviews/consumer/include/flexcdc.php on line 212
Could not connect to MySQL server:

**Comment by greenlion** [comment]
This issue is fixed in the latest checkin.  I verified that no warnings are issued and that connections via the socket work by switching my MySQL server to use port 3307, and using host=localhost and no port option.

**Comment by greenlion** [comment]
You will still need to provide the username.  You can only connect as the same username as the OS user connecting to the socket.

**Comment by gla1** [comment]
Oh of course, and that's what the initial failure message up at the top was about. This was a verification of your suggested configuration that only displayed host. I also subsequently tested with username, no dice. 

I'll build and test the latest version immediately. Thanks very much for the quick fix!

**Comment by greenlion** [comment]
I strive for good service, because I like it when people use my tools, and I want them to be able to use them.  My tools get very little word of mouth.  If you have the opportunity to blog about them sometime, and how they help you get things done, I'd appreciate it.  Here is an example: https://sokrati.com/blog/a-history-of-hades/
