### ISSUE TITLE
Potential Misconfiguration

### ISSUE THREAD

**Issue by santolucito** [greenlion/swanhart-tools#154]
We are a group of researchers from Yale University building a tool to finding bugs in configurations files. To evaluate the effectiveness of our tool, we randomly selected 1000 open source configuration files to verify and are requesting feedback on our error report. Your file https://raw.githubusercontent.com/greenlion/swanhart-tools/7a21e6e870420f3f844ee3d222d2603729697abc/flexviews/consumer/test/mysqltest/my.cnf was among those files. When we ran our tool your file, it reported the following potential errors.

[TYPE ERROR: for keyword "innodb-buffer-pool-size"
 Found value:["64mb"]
 In the training set we saw: String 0 times, Path 0 times, Size 139 times, Int 0 times, Bool 0 times

INTEGER RELATION ERROR: Expected tmp-table-size[mysqld] >= server-id[mysqld] 
 Found values: ["tmp-table-size[mysqld]=1m","server-id[mysqld]=999"]
 In the training set we saw: ">=" 30 times, "<=" 1 times, "==" 0 times
]

The training set referenced in the report is taken from the industrial configuration files at https://github.com/tianyin/configuration_datasets. Note that even if your system is currently working, these bug may manifest itself only under large traffic loads or different system environments. 

If you feel the any of above errors may indeed cause problems either on your system, or a different system, please comment on this issue report in the space below. This will help use to improve our tool. If you do not believe this is a potential bug, please feel free to close this issue. If possible we would appreciate your feedback before July 27.

If you would like find out more about how we detected these bug, you can find the open source tool at https://github.com/santolucito/ConfigV. For a quick overview of this tool, you can watch this video at https://youtu.be/plliEh-5MpM. If you have further questions, or would like to get involved with this project, feel free to reach out over email at mark.santolucito@yale.edu.

Thank you for your time!

**Comment by greenlion** [comment]
not a bug
