### ISSUE TITLE
expected behavior on consumer_safe.sh being restarted

### ISSUE THREAD

**Issue by adhiemsumitro** [greenlion/swanhart-tools#155]
I'm using FlexCDC for feeding RabbitMQ.
My setup finally works, but I need to a confirmation on these : 
- Is it true that if  I `killed -9` `consumer_safe.sh` (and corresponding `run_consumer.php`)  then restarting it, the Flexcdc will start to read from binlog #1 ?
- Is there such mechanism so it remember the position of last replicated row ?
- In a such event (after being restarted) then the Flexcdc will flood the RabbitMQ but I saw reported speed of 28-29 messages per sec. Is it normal ?

**Comment by greenlion** [comment]
FlexCDC picks up in the binlog where it left off if you kill it.
