### ISSUE TITLE
unrecognized MySQL version '10.3.12-MariaDB-log'." 

### ISSUE THREAD

**Issue by edukondalugorla** [greenlion/swanhart-tools#163]
Hi, 
When i run the run_consumer shell script, I am getting below Error, Please help me.

"error from mysqlbinlog: ERROR: Could not find server version: Master reported unrecognized MySQL version '10.3.12-MariaDB-log'."

**Comment by greenlion** [comment]
I'll take a look as soon as I can.

**Comment by jhlindnerberlin** [comment]
i was struggeling with it, too. see this post: https://www.percona.com/blog/2018/10/04/the-importance-of-mysqlbinlog-version/
when you're using mariadb you need to take it's mysqlbinlog as well. do not use the MySQL mysqlbinlog...

**Comment by greenlion** [comment]
not a bug
