### ISSUE TITLE
COMPUTE dies after inserting rows with dml_type 1 (so before inserting -1)

### ISSUE THREAD

**Issue by jhlindnerberlin** [greenlion/swanhart-tools#164]
**Edit**: sorry, was asking too fast. I had to first activate the SQL-Log to see what the proc is doing while computing the delta (quite obvious that this could be a good idea, haven't seen it). Then I was able to analyze the queries executed during the refresh. The last one, computing the dml_type=-1 entries, was very slow... but I just didn't carefully check what happens when adding expressions to an MV. I have a JOIN in there. While a GROUP adds automatically a key, a JOIN doesn't. After adding a key on the id fields it's fine now. 

---

First of all: the whole thing works fine. I'm currently testing it on a (fresh) sales database with some million rows, growing by let's say 50-100k rows per day, which is around 10k per hour. After every hour i want to aggregate the sales data (after a day aggregating the hours; same for week, month...). So I enabled the MV with a test aggregation which ended up in a 1.5 million rows mv-table (~300mb). While inserting ~25k rows (like testing one "heavy hour") in the underlaying table, the flexCDC writing (in the corresponding changelog) worked like a charm. And the refresh COMPUTE on that specific mv (performed on a poor sandbox environment) came back within 90 seconds.

Now: the insertion of all rows with dml_type=1 in the _delta-table seems to be very fast. I did no measurement, but after calling the refresh proc, all delta entries dml_type=1 have been inserted at least within seconds. But the COMPUTE refresh ends not til inserting the entries with dml_type=-1 (minus 1). At first glance it seemed to me that computing these entries is very costly... After ~90 secs the _delta-table had them inserted (APPLY was very fast btw.). 
After that I did another random insertion with ~2500k rows (10 times first test, but evenly spread to the period of a month, so many hours need to be aggregated at once now). All changes have been logged fast again. Also, the COMPUTE refresh brought me the dml_type=1 entries so damn fast (again within seconds). But after an hour I killed the refresh; it didn't come back. (however, the delta-entries stayed and the APPLY worked).

My question is: **what could be the bottleneck here? What makes the COMPUTE so costly?** Can I do some easy debugging? I tried to see what's happening in the proc; read also the execute_refresh_step-proc, but to be honest: I don't get it.

**Comment by greenlion** [comment]
It has honestly been a long time since I touched Flexviews, as it is
feature complete and stable.  I believe that you can SET @MV_DEBUG = TRUE;
This will then populate a table in the flexviews schema with messages about
each step and associated timing information.  My guess is that you need an
index on the materialized view log table(s) but I can't be sure.

**Comment by greenlion** [comment]
Not a bug.
