### ISSUE TITLE
Seeing this in flexviews error logs `Unknown column 'INF' in 'field list'`

### ISSUE THREAD

**Issue by korlaxxalrok** [greenlion/swanhart-tools#167]
Hello,

I know this isn't a support channel, and also that this software is mostly dormant (thought quite useful!), but I was wondering if anyone might have insight into this error. I seem to have flexviews up and running, but I'm getting this error on one of my tables.

```
INSERT INTO `flexviews`.`mvlog_17c32d22d5cf9990e23fb4c6255766eb` VALUES
Unknown column 'INF' in 'field list'
```

It looks like where there should be a change tracking identifier of some kind there is instead a HUGE number being inserted (if that makes sense). I'm not an expert user with this, just trying to copy and migrate an existing flexviews setup.

Thanks in advance for any insight(s).

**Comment by greenlion** [comment]
Looks like a bug in FlexCDC where PHP is treating a large value as
infinity, but I can't be sure.

Man it has literally been years since I looked at FlexCDC, but I think if
you edit the PHP file that you can set the debug bar to true and it will
print the SQL.  It should also print the mysqlbinlog command.  Collect the
output of both and post them here and I will take a look ASAP.

Thanks for using my tools!

--greenlion

**Comment by korlaxxalrok** [comment]
Howdy, thanks for popping in 👍 

Which PHP file has the debug option?

And yes!, absolutely happy to use your tools :) Thanks for making them, we've been running them for a few years now. I'm trying to migrate an existing setup to a new environment, but with a newer version of FlexCDC and PHP. I may have to rethink some of this, and I may be able to get the older version of PHP running if necessary.

**Comment by greenlion** [comment]
Hmm. Replying via email didn't work!

Update include/flexcdc.php and change the $debug variable in the function that runs SQL statements from $debug = false to $debug = true.

**Comment by korlaxxalrok** [comment]
I'm going to close this issue for now. See my comment in the other issue for an update.

Spoiler: Things seem to be working now 👍 

Thanks for your help! 🙇
