### ISSUE TITLE
Error for incompatible expr types

### ISSUE THREAD

**Issue by santec** [greenlion/swanhart-tools#28]
A possible enhancement:

* When adding a COLUMN expr, add_expr() will raise an error if there are GROUP or aggregate exprs.
* When adding a GROUP or MAX-like expr, add_expr() will raise an error if there are COLUMN exprs.
* If a GROUP expr is identical to a COLUMN expr, the latter will be ignored (no error is needed)

**Comment by greenlion** [comment]
Currently code converts COLUMN to GROUP if any aggregates are added, and GROUP are treated as COLUMN if there are no aggregates.  

I am closing this, but if you really think that the code should raise errors for these conditions let me know and I will look at it again.
