### ISSUE TITLE
ERROR: ERROR: SIGNAL ID NOT FOUND (FlexCDC consumer is likely behind)

### ISSUE THREAD

**Issue by GuyPaddock** [greenlion/swanhart-tools#41]
I am able to set-up an incremental MV from a query just fine, but when I try to refresh it using:

```
call flexviews.refresh(flexviews.get_id('theredpool_drupal', 'mv_user_round_summary')); 
```

I get:

```
ERROR 1054 (42S22): Unknown column 'ERROR: ERROR: SIGNAL ID NOT FOUND (FlexCDC consumer is likely behind)' in 'field list'
```

Even though I have verified that consumer_safe.sh is running.

**Comment by jamiejackson** [comment]
Is [this](https://bugs.mysql.com/bug.php?id=65812) the MySQL bug you mentioned, @greenlion? I'm guessing that this is what's giving me the same error (`Error Code: 1644. ERROR: SIGNAL ID NOT FOUND (FlexCDC consumer is likely behind)`) on MariaDB 5.5.44.

**Comment by greenlion** [comment]
Hi,

Yes, though there is a second error reported by someone else with a
slightly different but related problem.  A modern 5.6 mysqlbinlog will fix
the problem, even if you are using mariadb.  just get the binary tarball
and set mysqlbinlog=/path/to/5.6/mysqlbinlog in your consumer.ini.   You
/may/ have to set Flexviews back up again.  Just drop the flexviews
database and re-setup FlexCDC and Flexviews.

--justin
