### ISSUE TITLE
Flexviews is setup successfully but doesn't work

### ISSUE THREAD

**Issue by afarnoosh** [greenlion/swanhart-tools#67]
Flexviews installs and is set up successfully with no errors but once a table is added using the php script, nothing happens. None of the steps on the following blog fail: http://www.mysqlperformanceblog.com/2011/03/25/using-flexviews-part-two-change-data-capture/.

I'm at a loss as to what should be done next to debug this as the error log shows nothing and at no point during the setup or the subsequent inserts is an error thrown.

MySQL Server version: 5.5.34
Ubuntu 12.04

**Comment by neshwill** [comment]
Hi , i have same problem . 

root@usql2:/flexviews/consumer/mv# cat mv_create.sql 
CALL flexviews.create('config', 'mv', 'INCREMENTAL');
SET @mvid := LAST_INSERT_ID();
CALL flexviews.add_expr(@mvid,'COLUMN','filter_name','filter_name');
CALL flexviews.add_expr(@mvid,'COLUMN','value_new','value_new');

CALL flexviews.add_table(@mvid,'config','enumerations_vw','enumerations_vw',NULL);
CALL flexviews.add_expr(@mvid,'WHERE','filter_name = \'\' yyy \'\'','where_clause');
CALL flexviews.enable(@mvid);

root@usql2:/flexviews/consumer/mv# mysql -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 86
Server version: 5.6.22-71.0-log Percona Server (GPL), Release 71.0, Revision 726

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> call flexviews.enable(flexviews.get_id('config','mv'));
ERROR 1644 (45000): COULD NOT VALIDATE MATERIALIZED VIEW.  CHECK @MV_DEBUG.
mysql> 

mysql> select @MV_DEBUG
    -> ;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @MV_DEBUG                                                                                                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SELECT  NULL as mview$pk, (filter_name) as `filter_name`, (value_new) as `value_new`, (crc32(concat(filter_name,value_new))) as `mview$hash`
FROM  config.enumerations_vw as `enumerations_vw`  WHERE filter_name = '' yyy '' LIMIT 0 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by greenlion** [comment]
Hi, 

The problem is your filter condition.  See how the quotes are replaced?  Try using "abc" instead of \' and/or make sure you don't have too many \'

**Comment by mvid** [comment]
Hi, if you put your code in code blocks using the ``` markdown notation, you won't spam users who have usernames in your code :)

**Comment by neshwill** [comment]
)) Sorry , anyway nice to meet you !

**Comment by neshwill** [comment]
so now vm is created , but  not refreshed . i start ''' php ./setup_flexcdc.php --ini consumer.ini '''  and i see the process , but created view is not refreshed when i add or remove rows from table.  when i try to refresh in manually i just get '''all flexviews.refresh(flexviews.get_id('config','mv'),'BOTH', NULL); ''' 
ERROR 1644 (45000): ERROR: SIGNAL_ID not found(FlexCDC is not running or is behind) OR the specified mview:1 does not exist."

**Comment by greenlion** [comment]
We have had this discussion - flexviews predates this code convention and most users are not going to put example code in backticks.  

Complaining to this user won't stop the next one from doing the same.

**Comment by greenlion** [comment]
The consumer is probably not working.  Check flexviews.binlog_consumer_status

You probably have DECIMAL columns.  Make sure you use mysqlbinlog from recent 5.6 release of MySQL if you are using MySQL <=5.6.15 (I think) or MariaDB (any version)
