### ISSUE TITLE
Php -v 5.5.3

### ISSUE THREAD

**Issue by idevin** [greenlion/swanhart-tools#68]
when ru consumer_safe.sh with php version 5.5.3

Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /usr/share/php/Console/Getopt.php on line 109
PHP Strict Standards:  Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /usr/share/php/Console/Getopt.php on line 154
PHP Strict Standards:  Non-static method PEAR::isError() should not be called statically in swanhart-tools/flexviews/consumer/run_consumer.php on line 39
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in swanhart-tools/flexviews/consumer/include/flexcdc.php on line 140
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in swanhart-tools/flexviews/consumer/include/flexcdc.php on line 143

**Comment by greenlion** [comment]
I fixed the getopt/pear error today in the setup script.  I think I fixed it in the other scripts but will double check.

Conversion to mysqli_* was completed some time ago.
