### ISSUE TITLE
Flexview does not update mvlogs 

### ISSUE THREAD

**Issue by leosiuk** [greenlion/swanhart-tools#83]
Hello,

I installed flexview without errors, configured .ini file appropriately. Flex creates mvlogs table with mapping:
cdc	foo	mvlog_cf2334a9995f95d9d66580fc7176b113	1
cdc	mvlogs	mvlog_39a8778cab4301203fc502eaef13b402	1
It auto_changelog is set true and works. ( as I add new tables, they instantly appear in mvlogs)
But actual changes in tables are in inserted in mvlogs_xxxx tables. 
No error is returned.
Any advice there I should look for answer?

MySQL  5.1.73
PHP 5.3.3 

Edit: when I run "run_consumer.php" I get
-- /usr/bin/mysqlbinlog --port=3306 --user=vv_cdc --password=cdc --host=192.168.200.160 --base64-output=decode-rows -v -R --start-position=3401 --stop-position=4176 mysql-bin.000006 2>&1
Does it stuck those positions?

**Comment by greenlion** [comment]
can't duplicate.
